const Project = require("../models/Project");
const Building = require("../models/Building");
const Unit = require("../models/Unit");
const Booking = require("../models/Booking");

async function listProjects(req, res, next) { try { const page = Math.max(Number.parseInt(req.query.page, 10) || 1, 1); const limit = Math.min(Math.max(Number.parseInt(req.query.limit, 10) || 10, 1), 100); const search = req.query.search ? req.query.search.trim() : ""; const filter = search ? { $or: [{ name: { $regex: search, $options: "i" } }, { location: { $regex: search, $options: "i" } }, { description: { $regex: search, $options: "i" } }] } : {}; const [data, total] = await Promise.all([Project.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), Project.countDocuments(filter)]); res.json({ success: true, data, total, page, limit, totalPages: Math.ceil(total / limit) }); } catch (error) { next(error); } }
async function getProject(req, res, next) { try { const data = await Project.findById(req.params.id); if (!data) return res.status(404).json({ success: false, message: "Project not found" }); res.json({ success: true, data }); } catch (error) { next(error); } }
async function createProject(req, res, next) { try { const data = await Project.create(req.body); res.status(201).json({ success: true, message: "Project created successfully", data }); } catch (error) { next(error); } }
async function updateProject(req, res, next) { try { const data = await Project.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!data) return res.status(404).json({ success: false, message: "Project not found" }); res.json({ success: true, message: "Project updated successfully", data }); } catch (error) { next(error); } }
async function deleteProject(req, res, next) { try { const project = await Project.findById(req.params.id); if (!project) return res.status(404).json({ success: false, message: "Project not found" }); const buildings = await Building.find({ projectId: project._id }).select("_id"); const buildingIds = buildings.map((building) => building._id); const units = await Unit.find({ buildingId: { $in: buildingIds } }).select("_id"); const unitIds = units.map((unit) => unit._id); if (unitIds.length > 0) await Booking.deleteMany({ unitId: { $in: unitIds } }); if (unitIds.length > 0) await Unit.deleteMany({ _id: { $in: unitIds } }); if (buildingIds.length > 0) await Building.deleteMany({ _id: { $in: buildingIds } }); await project.deleteOne(); res.json({ success: true, message: "Project and all related buildings, units, and bookings deleted successfully" }); } catch (error) { next(error); } }

module.exports = { listProjects, getProject, createProject, updateProject, deleteProject };