const swaggerDocument = {
    openapi: "3.0.0",
    info: { title: "Real Estate CRM API", version: "1.0.0", description: "Backend API for the Real Estate CRM." },
    servers: [
    {
        url: process.env.API_URL || "http://localhost:5000"
    }
],
    components: {
        securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" }, setupKey: { type: "apiKey", in: "header", name: "X-Setup-Key", description: "One-time key from INITIAL_ADMIN_SETUP_KEY" } },
        schemas: {
            InitialAdmin: { type: "object", required: ["name", "mobileNumber", "email", "password"], properties: { name: { type: "string" }, mobileNumber: { type: "string" }, email: { type: "string", format: "email" }, password: { type: "string", minLength: 6 } } },
            CreateUser: { type: "object", required: ["name", "mobileNumber", "email", "password", "role"], properties: { name: { type: "string" }, mobileNumber: { type: "string" }, email: { type: "string", format: "email" }, password: { type: "string", minLength: 6 }, role: { type: "string", enum: ["SUPER_ADMIN", "ADMIN", "LIMITED_ADMIN", "SALES_EMPLOYEE"] } } },
            UpdateUser: { type: "object", properties: { name: { type: "string" }, mobileNumber: { type: "string" }, email: { type: "string", format: "email" }, password: { type: "string", minLength: 6 }, role: { type: "string", enum: ["SUPER_ADMIN", "ADMIN", "LIMITED_ADMIN", "SALES_EMPLOYEE"] } } },
            Login: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string" } } },
            Lead: { type: "object", required: ["name", "phone", "stage"], properties: { name: { type: "string" }, phone: { type: "string" }, email: { type: "string", format: "email" }, stage: { type: "string", enum: ["New", "Contacted", "Site Visit", "Interested", "Negotiation", "Booked", "Lost"] }, assignedTo: { type: "string" }, followUpDate: { type: "string", format: "date" }, notes: { type: "string" } } },
            Project: { type: "object", required: ["name", "location"], properties: { name: { type: "string" }, location: { type: "string" }, description: { type: "string" } } },
            Building: { type: "object", required: ["name"], properties: { name: { type: "string" } } },
            Unit: { type: "object", required: ["unitNumber", "type", "price"], properties: { unitNumber: { type: "string" }, type: { type: "string", enum: ["1BHK", "2BHK", "3BHK"] }, price: { type: "number", minimum: 0 }, status: { type: "string", enum: ["AVAILABLE", "BOOKED"] } } },
            Booking: { type: "object", required: ["leadId", "unitId", "bookingDate"], properties: { leadId: { type: "string" }, unitId: { type: "string" }, bookingDate: { type: "string", format: "date" } } }
        }
    },
    paths: {
        "/api/auth/setup": { post: { tags: ["Auth"], summary: "Create the first SUPER_ADMIN once", security: [{ setupKey: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/InitialAdmin" } } } }, responses: { 201: { description: "Initial SUPER_ADMIN created" }, 401: { description: "Invalid setup key" }, 409: { description: "Initial admin already exists" }, 503: { description: "Setup is not configured" } } } },
        "/api/auth/login": { post: { tags: ["Auth"], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/Login" } } } }, responses: { 200: { description: "Login successful" }, 401: { description: "Invalid credentials" } } } },
        "/api/auth/me": { get: { tags: ["Auth"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Current user" } } } },
        "/api/leads": { get: { tags: ["Leads"], security: [{ bearerAuth: [] }], parameters: [{ name: "page", in: "query", schema: { type: "integer", default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", default: 10, maximum: 100 } }, { name: "search", in: "query", schema: { type: "string" } }, { name: "stage", in: "query", schema: { type: "string" } }, { name: "assignedTo", in: "query", schema: { type: "string" } }], responses: { 200: { description: "Paginated lead list" } } }, post: { tags: ["Leads"], security: [{ bearerAuth: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/Lead" } } } }, responses: { 201: { description: "Lead created" }, 400: { description: "Validation error" } } } },
        "/api/leads/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], get: { tags: ["Leads"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Lead" } } }, put: { tags: ["Leads"], security: [{ bearerAuth: [] }], requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/Lead" } } } }, responses: { 200: { description: "Lead updated" } } }, delete: { tags: ["Leads"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Lead deleted" } } } },
        "/api/projects": { get: { tags: ["Projects"], security: [{ bearerAuth: [] }], parameters: [{ name: "page", in: "query", schema: { type: "integer", default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", default: 10, maximum: 100 } }, { name: "search", in: "query", description: "Search by project name, location, or description", schema: { type: "string" } }], responses: { 200: { description: "Paginated projects" } } }, post: { tags: ["Projects"], security: [{ bearerAuth: [] }], requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/Project" } } } }, responses: { 201: { description: "Created" } } } },
        "/api/projects/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], get: { tags: ["Projects"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Project" } } }, put: { tags: ["Projects"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Updated" } } }, delete: { tags: ["Projects"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Deleted" } } } },
        "/api/projects/{projectId}/buildings": { parameters: [{ name: "projectId", in: "path", required: true, schema: { type: "string" } }], get: { tags: ["Buildings"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Buildings for the project" } } }, post: { tags: ["Buildings"], security: [{ bearerAuth: [] }], requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/Building" } } } }, responses: { 201: { description: "Created" } } } },
        "/api/buildings/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], put: { tags: ["Buildings"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Updated" } } }, delete: { tags: ["Buildings"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Deleted" } } } },
        "/api/buildings/{buildingId}/units": { parameters: [{ name: "buildingId", in: "path", required: true, schema: { type: "string" } }], get: { tags: ["Units"], security: [{ bearerAuth: [] }], parameters: [{ name: "status", in: "query", schema: { type: "string", enum: ["AVAILABLE", "BOOKED"] } }], responses: { 200: { description: "Units for the building" } } }, post: { tags: ["Units"], security: [{ bearerAuth: [] }], requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/Unit" } } } }, responses: { 201: { description: "Created" } } } },
        "/api/units/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], put: { tags: ["Units"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Updated" } } }, delete: { tags: ["Units"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Deleted" } } } },
        "/api/bookings": { get: { tags: ["Bookings"], security: [{ bearerAuth: [] }], parameters: [{ name: "page", in: "query", schema: { type: "integer", default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", default: 10, maximum: 100 } }, { name: "search", in: "query", description: "Search customer/lead name, phone, email, unit, building, or project", schema: { type: "string" } }], responses: { 200: { description: "Paginated bookings" } } }, post: { tags: ["Bookings"], security: [{ bearerAuth: [] }], requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/Booking" } } } }, responses: { 201: { description: "Booked" }, 409: { description: "Unit already booked" } } } },
        "/api/bookings/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], get: { tags: ["Bookings"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Booking" } } } },
        "/api/dashboard": { get: { tags: ["Dashboard"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Dashboard statistics" } } } },
        "/api/employees": { get: { tags: ["Employees"], security: [{ bearerAuth: [] }], parameters: [{ name: "page", in: "query", schema: { type: "integer", default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", default: 10 } }, { name: "search", in: "query", description: "Search by name or mobile number", schema: { type: "string" } }], responses: { 200: { description: "Paginated employee list" } } }, post: { tags: ["Employees"], security: [{ bearerAuth: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CreateUser" } } } }, responses: { 201: { description: "User created" }, 409: { description: "Email already registered" } } } },
        "/api/employees/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], get: { tags: ["Employees"], security: [{ bearerAuth: [] }], responses: { 200: { description: "Employee details" }, 404: { description: "User not found" } } }, put: { tags: ["Employees"], security: [{ bearerAuth: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateUser" } } } }, responses: { 200: { description: "User updated" } } }, delete: { tags: ["Employees"], security: [{ bearerAuth: [] }], responses: { 200: { description: "User deleted" } } } },
        "/api/users": { get: { tags: ["Users"], security: [{ bearerAuth: [] }], parameters: [{ name: "page", in: "query", schema: { type: "integer", default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", default: 10 } }, { name: "search", in: "query", description: "Search by name or mobile number", schema: { type: "string" } }], responses: { 200: { description: "Paginated user list" } } }, post: { tags: ["Users"], security: [{ bearerAuth: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CreateUser" } } } }, responses: { 201: { description: "User created" }, 403: { description: "Insufficient role permission" } } } },
        "/api/users/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], get: { tags: ["Users"], security: [{ bearerAuth: [] }], responses: { 200: { description: "User details" } } }, put: { tags: ["Users"], security: [{ bearerAuth: [] }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateUser" } } } }, responses: { 200: { description: "User updated" } } }, delete: { tags: ["Users"], security: [{ bearerAuth: [] }], responses: { 200: { description: "User deleted" } } } }
    }
};

module.exports = swaggerDocument;